# Generated by Django 3.0.4 on 2020-07-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200726_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images'),
        ),
    ]
