# Generated by Django 3.0.4 on 2020-07-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200728_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Contact_No', models.IntegerField()),
                ('purpose', models.CharField(choices=[('Weddings', 'Weddings'), ('Events', 'Events'), ('Others', 'Others')], max_length=120)),
                ('requirements', models.TextField(null=True)),
            ],
        ),
    ]
