# Generated by Django 3.0.4 on 2020-07-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Contact_No',
            field=models.CharField(default='+91-', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='purpose',
            field=models.CharField(choices=[('Weddings', 'Weddings'), ('Events', 'Events'), ('Product Shoot', 'Product Shoot'), ('Food Photography', 'Food Photography'), ('Fashion Photography', 'Fashion Photography'), ('Others', 'Others')], default='Events', max_length=120),
        ),
    ]
